package com.bernardawj.notey.enums;

public enum NotificationType {

    PROJECT_INVITATION,
    PROJECT_REMOVAL,
    PROJECT_ACCEPTANCE,
    PROJECT_REJECTION,
    TASK_ALLOCATION,
    TASK_ALLOCATION_REMOVAL,
    TASK_MARK_COMPLETED,
    TASK_MARK_INCOMPLETE
}
